"""Tests for the caption-blocker diagnostic's pure logic.

The probes themselves need yt-dlp and an authenticated session, so they run on
the operator's machine. The parsing, track selection, outcome classification,
and hypothesis ranking are pure and are tested here against fixtures.
"""

from __future__ import annotations

import unittest

from transcripts.diagnose_captions import (
    classify_fetch,
    is_probably_asr,
    parse_list_subs,
    pick_manual_track,
    summarize,
)

LIST_SUBS = """[youtube] Extracting URL: https://www.youtube.com/watch?v=MBjio010l60
Available automatic captions for MBjio010l60:
Language Name          Formats
en       English (auto-generated)  vtt, srt
es       Spanish (auto-generated)  vtt

Available subtitles for MBjio010l60:
Language Name        Formats
en-US    English CC1  vtt, srt
"""

NO_MANUAL = """Available automatic captions for X:
Language Name                     Formats
en       English (auto-generated)  vtt

Available subtitles for X:
"""


class ParseListSubsTest(unittest.TestCase):
    def test_separates_manual_from_automatic(self):
        parsed = parse_list_subs(LIST_SUBS)
        self.assertEqual([t["code"] for t in parsed["manual"]], ["en-US"])
        self.assertEqual(sorted(t["code"] for t in parsed["automatic"]), ["en", "es"])

    def test_handles_no_manual_section_content(self):
        parsed = parse_list_subs(NO_MANUAL)
        self.assertEqual(parsed["manual"], [])
        self.assertEqual(len(parsed["automatic"]), 1)

    def test_ignores_header_and_bracket_lines(self):
        codes = [t["code"] for t in parse_list_subs(LIST_SUBS)["manual"]]
        self.assertNotIn("Language", codes)
        self.assertFalse(any(c.startswith("[") for c in codes))


class TrackSelectionTest(unittest.TestCase):
    def test_detects_autogenerated_tracks(self):
        self.assertTrue(is_probably_asr("English (auto-generated)", "en"))
        self.assertTrue(is_probably_asr("English", "en-orig"))
        self.assertFalse(is_probably_asr("English CC1", "en-US"))

    def test_prefers_the_manual_cart_track(self):
        parsed = parse_list_subs(LIST_SUBS)
        chosen = pick_manual_track(parsed["manual"])
        self.assertEqual(chosen["code"], "en-US")

    def test_never_selects_an_asr_track(self):
        asr_only = [{"code": "en", "name": "English (auto-generated)", "formats": "vtt"}]
        self.assertIsNone(pick_manual_track(asr_only))

    def test_returns_none_when_nothing_is_declared(self):
        self.assertIsNone(pick_manual_track([]))


class ClassifyFetchTest(unittest.TestCase):
    def test_zero_bytes_on_a_declared_track_is_the_reported_symptom(self):
        self.assertEqual(
            classify_fetch(declared=True, returncode=0, http_status=200, byte_count=0),
            "zero_byte",
        )

    def test_bytes_returned_is_ok(self):
        self.assertEqual(
            classify_fetch(declared=True, returncode=0, http_status=200, byte_count=4096),
            "ok",
        )

    def test_undeclared_track_is_distinct_from_zero_byte(self):
        # This distinction is the whole point: "not offered" and "offered but
        # empty" must never collapse into "no captions".
        self.assertEqual(
            classify_fetch(declared=False, returncode=0, http_status=None, byte_count=None),
            "not_offered",
        )

    def test_transport_failure_is_distinct(self):
        self.assertEqual(
            classify_fetch(declared=True, returncode=1, http_status=None, byte_count=0),
            "fetch_failed",
        )

    def test_empty_body_with_an_error_status_is_distinct(self):
        self.assertEqual(
            classify_fetch(declared=True, returncode=0, http_status=403, byte_count=0),
            "empty_with_error",
        )


def rows(*specs):
    return [
        {"video_id": v, "player_client": c, "outcome": o, "asr_track_count": a}
        for v, c, o, a in specs
    ]


class SummarizeTest(unittest.TestCase):
    def test_a_working_client_rules_out_an_empty_upstream_asset(self):
        summary = summarize(rows(
            ("MBjio010l60", "web", "zero_byte", 1),
            ("MBjio010l60", "tv", "ok", 1),
        ))
        self.assertEqual(summary["working_clients"], ["tv"])
        self.assertTrue(summary["control_recovered"])
        self.assertTrue(any("client-gating" in f for f in summary["findings"]))
        self.assertFalse(any("ASR" in f and "needed" not in f for f in summary["findings"]))

    def test_control_failing_everywhere_points_at_a_regression(self):
        summary = summarize(rows(
            ("MBjio010l60", "web", "zero_byte", 1),
            ("MBjio010l60", "tv", "zero_byte", 1),
        ))
        self.assertFalse(summary["control_recovered"])
        self.assertTrue(any("regression" in f for f in summary["findings"]))

    def test_all_zero_byte_still_forbids_calling_captions_absent(self):
        summary = summarize(rows(("2Wm-11hPNns", "web", "zero_byte", 2)))
        self.assertTrue(
            any("do not record them as having no captions" in f
                for f in summary["findings"])
        )

    def test_reports_asr_availability_without_recommending_it(self):
        summary = summarize(rows(("2Wm-11hPNns", "web", "zero_byte", 2)))
        self.assertEqual(summary["asr_available_but_not_approved"], ["2Wm-11hPNns"])

    def test_nothing_declared_is_reported_as_a_different_failure(self):
        summary = summarize(rows(("X", "web", "not_offered", 0)))
        self.assertTrue(any("different" in f for f in summary["findings"]))


if __name__ == "__main__":
    unittest.main()
