#!/usr/bin/env python3
"""Characterize the M3.1 zero-byte manual-caption blocker.

Three separate videos -- the target August 18 regular session `2Wm-11hPNns`,
committee video `1GWlqG-UJHE`, and the previously-indexed control
`MBjio010l60` -- all declare a manual English CC1/CART track whose payload
comes back HTTP 200 with zero bytes. The control is the important one: those
captions were successfully ingested before, so the corpus JSON proves the
track used to download. That points at an upstream or client-side regression
rather than three independent per-video gaps.

This script does not decide anything. It gathers evidence to separate the
competing explanations:

  yt-dlp regression      the installed yt-dlp no longer negotiates the manual
                         track correctly -> a different version behaves better.
  player-client rotation YouTube served the track to some innerturbe clients
                         and not others -> some --extractor-args player_client
                         value still returns bytes.
  auth/cookie state      the track needs a signed-in session that is not being
                         attached -> the request is being downgraded.
  genuine upstream pull  the caption asset really is empty for everyone, on
                         every client and version.

Only the last of those would justify reopening the ASR question, and even then
that is the user's call, not this script's.

Run it where an authenticated yt-dlp session exists (the Mac with the working
cookie jar), NOT in CI. It writes a JSON report with no credentials in it: the
cookie path is recorded as a boolean, never a value, and track URLs are hashed
rather than stored, since a caption URL carries a signed access token.

    python3 diagnose_captions.py --out captions_diagnosis.json \
        --cookies-from-browser chrome

Add --video ID to probe extra recordings; the three known cases are default.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import shutil
import subprocess
import sys
import time
from pathlib import Path
from typing import Any

# The control was ingested successfully before, so a zero-byte result for it is
# the strongest signal that something regressed rather than never existing.
KNOWN_VIDEOS = {
    "MBjio010l60": "control: previously ingested successfully",
    "2Wm-11hPNns": "target: missing 10th regular session, 2026-08-18",
    "1GWlqG-UJHE": "representative standing-committee meeting",
}

# YouTube has rotated which innertube clients receive caption tracks more than
# once; probing several separates a client-gating change from an empty asset.
PLAYER_CLIENTS = ("web", "web_safari", "mweb", "android", "ios", "tv")

MANUAL_TRACK_HINTS = ("cc1", "cart", "en-us", "en")
ASR_MARKERS = ("auto-generated", "automatic", "-orig", "asr")


# --------------------------------------------------------------------------
# pure helpers (unit-tested; no subprocess)
# --------------------------------------------------------------------------
def is_probably_asr(track_name: str, track_code: str) -> bool:
    """True when a listed track is autogenerated rather than manual CART."""
    blob = f"{track_name} {track_code}".lower()
    return any(marker in blob for marker in ASR_MARKERS)


def parse_list_subs(stdout: str) -> dict[str, list[dict[str, str]]]:
    """Parse `yt-dlp --list-subs` output into manual and automatic track lists.

    yt-dlp prints two sections; only the manual one matters here, but the
    automatic section is recorded so the report can state plainly whether an
    ASR alternative exists without implying it should be used.
    """
    manual: list[dict[str, str]] = []
    automatic: list[dict[str, str]] = []
    target: list[dict[str, str]] | None = None
    for line in stdout.splitlines():
        stripped = line.strip()
        low = stripped.lower()
        if "available automatic captions" in low:
            target = automatic
            continue
        if "available subtitles" in low:
            target = manual
            continue
        if not stripped or target is None:
            continue
        if low.startswith("language") or stripped.startswith("["):
            continue
        parts = re.split(r"\s{2,}", stripped)
        if len(parts) < 2:
            continue
        code, formats = parts[0], parts[-1]
        name = parts[1] if len(parts) > 2 else ""
        target.append({"code": code, "name": name, "formats": formats})
    return {"manual": manual, "automatic": automatic}


def pick_manual_track(manual: list[dict[str, str]]) -> dict[str, str] | None:
    """Choose the English manual/CART track a CART ingest would want."""
    candidates = [t for t in manual if not is_probably_asr(t["name"], t["code"])]
    for hint in MANUAL_TRACK_HINTS:
        for track in candidates:
            if hint in f"{track['code']} {track['name']}".lower():
                return track
    return candidates[0] if candidates else None


def classify_fetch(*, declared: bool, returncode: int, http_status: int | None,
                   byte_count: int | None) -> str:
    """Classify one caption fetch attempt into a comparable outcome."""
    if not declared:
        return "not_offered"
    if returncode != 0 and byte_count in (None, 0):
        return "fetch_failed"
    if byte_count == 0:
        # The distinguishing symptom: the server acknowledges the request but
        # sends no payload.
        return "zero_byte" if http_status in (None, 200) else "empty_with_error"
    if byte_count and byte_count > 0:
        return "ok"
    return "unknown"


def summarize(results: list[dict[str, Any]]) -> dict[str, Any]:
    """Rank the competing explanations against what the probes actually found."""
    by_outcome: dict[str, int] = {}
    for row in results:
        by_outcome[row["outcome"]] = by_outcome.get(row["outcome"], 0) + 1

    ok_rows = [r for r in results if r["outcome"] == "ok"]
    declared_rows = [r for r in results if r["outcome"] != "not_offered"]
    control_rows = [r for r in results if r["video_id"] == "MBjio010l60"]
    control_ok = [r for r in control_rows if r["outcome"] == "ok"]

    findings: list[str] = []
    if ok_rows:
        clients = sorted({r["player_client"] for r in ok_rows})
        findings.append(
            "MANUAL CAPTIONS ARE STILL RETRIEVABLE via player_client(s): "
            + ", ".join(clients)
            + ". This is a client-gating issue, not an empty upstream asset. "
              "Pin a working client in the ingest path; no ASR exception is needed."
        )
    elif control_rows and not control_ok:
        findings.append(
            "The previously-ingested control returned no bytes on every client "
            "probed. Since its captions were ingested before, the asset is not "
            "simply absent -- suspect a yt-dlp or auth regression before "
            "concluding the captions are gone upstream. Retry with a different "
            "yt-dlp version and a confirmed signed-in cookie jar."
        )
    if declared_rows and not ok_rows:
        findings.append(
            "Every declared manual track returned zero bytes. Record these "
            "meetings as blocked with a source-specific reason; do not record "
            "them as having no captions, because the track is still declared."
        )
    if not declared_rows:
        findings.append(
            "No manual track was declared at all on any probe -- a different "
            "failure from the zero-byte payload originally reported."
        )
    return {
        "outcomes": by_outcome,
        "working_clients": sorted({r["player_client"] for r in ok_rows}),
        "control_recovered": bool(control_ok),
        "findings": findings,
        "asr_available_but_not_approved": sorted({
            r["video_id"] for r in results if r.get("asr_track_count")
        }),
    }


# --------------------------------------------------------------------------
# probes (subprocess edge)
# --------------------------------------------------------------------------
def run(cmd: list[str], timeout: int = 120) -> subprocess.CompletedProcess:
    return subprocess.run(cmd, capture_output=True, text=True, timeout=timeout)


def probe(video_id: str, player_client: str, cookie_args: list[str],
          workdir: Path) -> dict[str, Any]:
    """List subtitles for one client, then try to download the manual track."""
    base = ["yt-dlp", "--skip-download", "--extractor-args",
            f"youtube:player_client={player_client}", *cookie_args]
    url = f"https://www.youtube.com/watch?v={video_id}"

    listed = run([*base, "--list-subs", url])
    tracks = parse_list_subs(listed.stdout)
    chosen = pick_manual_track(tracks["manual"])

    row: dict[str, Any] = {
        "video_id": video_id,
        "player_client": player_client,
        "manual_track_count": len(tracks["manual"]),
        "asr_track_count": len(tracks["automatic"]),
        "declared_track": chosen["code"] if chosen else None,
        "list_returncode": listed.returncode,
        "list_stderr_head": listed.stderr.strip().splitlines()[:2],
    }
    if chosen is None:
        row["outcome"] = classify_fetch(
            declared=False, returncode=listed.returncode,
            http_status=None, byte_count=None,
        )
        return row

    out_tpl = workdir / f"{video_id}.{player_client}"
    fetched = run([*base, "--write-sub", "--sub-langs", chosen["code"],
                   "--sub-format", "vtt", "-o", str(out_tpl), url])
    written = sorted(workdir.glob(f"{video_id}.{player_client}*"))
    byte_count = sum(p.stat().st_size for p in written) if written else 0
    row.update({
        "fetch_returncode": fetched.returncode,
        "fetch_stderr_head": fetched.stderr.strip().splitlines()[:3],
        "byte_count": byte_count,
        "files_written": [p.name for p in written],
        # A caption URL embeds a signed token, so only its digest is recorded.
        "track_url_sha256": hashlib.sha256(
            f"{video_id}:{chosen['code']}".encode()
        ).hexdigest()[:16],
        "outcome": classify_fetch(
            declared=True, returncode=fetched.returncode,
            http_status=200, byte_count=byte_count,
        ),
    })
    return row


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    parser.add_argument("--out", type=Path, required=True)
    parser.add_argument("--video", action="append", default=[],
                        help="extra video ID to probe (defaults cover the 3 known cases)")
    parser.add_argument("--cookies-from-browser", default=None,
                        help="passed straight to yt-dlp; the value is never written to the report")
    parser.add_argument("--cookies", type=Path, default=None,
                        help="cookie jar file; only its presence is recorded")
    parser.add_argument("--client", action="append", default=[],
                        help=f"player_client to probe (default: {', '.join(PLAYER_CLIENTS)})")
    parser.add_argument("--workdir", type=Path, default=Path("./caption_probe"),
                        help="scratch dir for downloaded payloads (keep it gitignored)")
    args = parser.parse_args(argv)

    if not shutil.which("yt-dlp"):
        print("yt-dlp not found on PATH; run this on the machine with the "
              "authenticated session", file=sys.stderr)
        return 2

    cookie_args: list[str] = []
    if args.cookies_from_browser:
        cookie_args += ["--cookies-from-browser", args.cookies_from_browser]
    if args.cookies:
        cookie_args += ["--cookies", str(args.cookies)]
    if not cookie_args:
        print("warning: no cookie source given; an unauthenticated probe cannot "
              "distinguish an auth downgrade from an empty asset", file=sys.stderr)

    videos = list(KNOWN_VIDEOS) + [v for v in args.video if v not in KNOWN_VIDEOS]
    clients = args.client or list(PLAYER_CLIENTS)
    args.workdir.mkdir(parents=True, exist_ok=True)

    version = run(["yt-dlp", "--version"]).stdout.strip()
    results: list[dict[str, Any]] = []
    for video_id in videos:
        for client in clients:
            print(f"[probe] {video_id} client={client}", flush=True)
            try:
                results.append(probe(video_id, client, cookie_args, args.workdir))
            except subprocess.TimeoutExpired:
                results.append({
                    "video_id": video_id, "player_client": client,
                    "outcome": "fetch_failed", "note": "timed out",
                })
            time.sleep(0.5)

    report = {
        "schema_version": "caption-diagnosis-v1",
        "generated_at": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
        "yt_dlp_version": version,
        "authenticated": bool(cookie_args),
        "videos": {v: KNOWN_VIDEOS.get(v, "additional probe") for v in videos},
        "player_clients": clients,
        "results": results,
        "summary": summarize(results),
    }
    args.out.write_text(json.dumps(report, indent=2))
    print(f"\n[probe] wrote {args.out}")
    for finding in report["summary"]["findings"]:
        print(f"[probe] {finding}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
